#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := AirController
CONFIG_COMPILER_CXX_RTTI := 1
include $(IDF_PATH)/make/project.mk

