//
// Created by lukaszk on 08.07.2020.
//
#include "driver/gpio.h"

#ifndef AIRCONTROLLER_PINS_H
#define AIRCONTROLLER_PINS_H

#define TEMPERATURE_PIN GPIO_NUM_2
#define ELECTRIC_METER_PIN_1 GPIO_NUM_4
#define ELECTRIC_METER_PIN_2 GPIO_NUM_5
#define INSIDE_AIR_USAGE_PIN GPIO_NUM_12
#define OUTSIDE_AIR_USAGE_PIN GPIO_NUM_13

#define ESP_INTR_FLAG_DEFAULT 0
#define MAX_DEVICES 2
#define DS18B20_USED_RESOLUTION (DS18B20_RESOLUTION_12_BIT)
#define SAMPLE_PERIOD 1000 // milliseconds

#endif // AIRCONTROLLER_PINS_H
